# Generated by Django 4.1.4 on 2022-12-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
