# Generated by Django 4.1.4 on 2022-12-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
