# Generated by Django 4.1.4 on 2023-01-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
