# Generated by Django 4.1.4 on 2023-01-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_subscriptionplan_sub_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='sub_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
