# Generated by Django 4.1.4 on 2023-01-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_subscriptionplan_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='no_job',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='no_staff',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
