# Generated by Django 4.1.4 on 2022-12-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(default='HWKDPY', max_length=100, primary_key=True, serialize=False),
        ),
    ]
