# Generated by Django 4.1.4 on 2022-12-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
