# Generated by Django 4.1.4 on 2023-01-10 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0003_alter_subscriptionplan_sub_name'),
        ('owner', '0010_purchaseplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseplan',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='purchaseplan',
            name='transact_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
