# Generated by Django 4.1.4 on 2023-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_alter_purchaseplan_owner_alter_purchaseplan_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseplan',
            name='is_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
