# Generated by Django 4.1.4 on 2023-01-15 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_purchaseplan_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseplan',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2024, 1, 15)),
        ),
    ]
