# Generated by Django 4.1.4 on 2022-12-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='passout',
        ),
    ]
