# Generated by Django 4.1.4 on 2022-12-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_education_passout'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='exp_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
