# Generated by Django 4.1.4 on 2023-02-19 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0007_alter_jobpost_job_expired'),
        ('userapp', '0005_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('app_status', models.CharField(choices=[('pending', 'pending'), ('selected', 'selected'), ('rejected', 'rejected')], default='pending', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('app_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.jobpost')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
