# Generated by Django 4.1.4 on 2023-02-19 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0007_alter_jobpost_job_expired'),
        ('userapp', '0006_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='app_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.jobpost'),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='app_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
