# Generated by Django 4.1.4 on 2023-01-15 04:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0014_alter_purchaseplan_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_salary', models.IntegerField(blank=True, null=True)),
                ('job_salaryto', models.IntegerField(blank=True, null=True)),
                ('job_type', models.CharField(blank=True, max_length=255, null=True)),
                ('job_qualif', models.CharField(blank=True, max_length=255, null=True)),
                ('job_descri', models.CharField(blank=True, max_length=255, null=True)),
                ('job_respon', models.CharField(blank=True, max_length=255, null=True)),
                ('job_requir', models.CharField(blank=True, max_length=255, null=True)),
                ('job_sechedule', models.CharField(blank=True, max_length=255, null=True)),
                ('job_relocate', models.CharField(blank=True, max_length=255, null=True)),
                ('job_education', models.CharField(blank=True, max_length=255, null=True)),
                ('job_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('job_posted', models.DateField(auto_now_add=True)),
                ('job_expired', models.DateField(default=datetime.date(2023, 1, 30))),
                ('is_active', models.BooleanField(default=True)),
                ('job_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.company')),
                ('job_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
