# Generated by Django 4.1.4 on 2023-01-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_jobpost_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_relocate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_sechedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
