# Generated by Django 4.1.4 on 2023-02-16 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_jobpost_job_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_expired',
            field=models.DateField(default=datetime.date(2023, 3, 3)),
        ),
    ]
